version: '2'

services:
  webserver:
    build: ./docker
    image: knubbe_php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../html:/var/www/html
      - ../logs:/var/www/logs
      - /home/knubbe/www/adminer:/var/www/html/adminer
      - ./docker/configs/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "4406:3306"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=eckero
